# Generated by Django 5.0.6 on 2024-06-14 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDocumentos',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposEspecialidades',
            fields=[
                ('id_tipo_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumerosDocumentos',
            fields=[
                ('id_numero_documento', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=20, null=True)),
                ('id_tipo_documento', models.ForeignKey(db_column='id_tipo_documento', null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.tiposdocumentos')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_numero_documento', models.ForeignKey(db_column='id_numero_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.numerosdocumentos')),
                ('id_tipo_especialidad', models.ForeignKey(db_column='id_tipo_especialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.tiposespecialidades')),
            ],
        ),
    ]
